### ISSUE TITLE
mod clash with mass bombardments 

### ISSUE THREAD

**Issue by Rex5522** [tk421storm/ragdoll#1]
the issue seems to occur when a large amount of explosions hit pawns, then it seems to enter a error loop repeating the same error over and over

EDIT: this seems to be purely a clash between mods. the errors only occur when both mods are present (ragdoll and auto morters)

heres the hugs lib log: https://gist.github.com/HugsLibRecordKeeper/59386fae4c30d4ed01e811e70cf23e0c
but i will also put two of the errors i saw down below. 
for tips on re-creating this issue install auto morters 
(https://steamcommunity.com/sharedfiles/filedetails/?id=2054073477&searchtext=)
and bomb a large group of pawns using around 50 morters (thats what i uses)
if you need additional context / help feel free to message me on discord: t_rex_5522

errors (may not be all of them):

Exception in Verse.AI.ThinkNode_PrioritySorter TryIssueJobPackage: System.NullReferenceException: Object reference not set to an instance of an object
[Ref 57E4B756] Duplicate stacktrace, see ref for original
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.AI.ThinkNode_PrioritySorter:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage (Verse.Pawn,Verse.AI.JobIssueParams)

System.NullReferenceException: Object reference not set to an instance of an object
[Ref 1C49981E]
 at RimWorld.SteadyEnvironmentEffects.TryDoDeteriorate (Verse.Thing t, System.Boolean roofed, System.Boolean roomUsesOutdoorTemperature, Verse.TerrainDef terrain) [0x00010] in <91ef6de66e7b4ba2839be0ab7f01fedf>:0 
 at RimWorld.SteadyEnvironmentEffects.DoCellSteadyEffects (Verse.IntVec3 c) [0x00122] in <91ef6de66e7b4ba2839be0ab7f01fedf>:0 
 at RimWorld.SteadyEnvironmentEffects.SteadyEnvironmentEffectsTick () [0x000c1] in <91ef6de66e7b4ba2839be0ab7f01fedf>:0 
 at Verse.Map.MapPostTick () [0x0004e] in <91ef6de66e7b4ba2839be0ab7f01fedf>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.Map:MapPostTick ()
Verse.TickManager:DoSingleTick ()
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
Verse.Root_Play:Update ()

**Comment by tk421storm** [comment]
this is great, thank you! are you able to run a test with "debug logging" enabled in ragdoll's mod settings? that would help me identify exactly which function is causing the issue. I'm pretty sure it has to do with tossing corpses, though, and this is probably the culprit - it's very hard to recreate on my end though:

Error while killing Witch during phase 5: System.NullReferenceException: Object reference not set to an instance of an object
[Ref 5B617C56]
 at TKS_Ragdoll.CompTossable.StopToss () [0x002b8] in <1772210073d94344a39a33fdeedc7cb9>:0 
 at TKS_Ragdoll.Thing_patches.Kill_prefix (Verse.DamageInfo dinfo, Verse.Hediff exactCulprit, Verse.Thing __instance) [0x0001b] in <1772210073d94344a39a33fdeedc7cb9>:0 
 at Verse.Thing.Kill (System.Nullable`1[T] dinfo, Verse.Hediff exactCulprit) [0x00019] in <91ef6de66e7b4ba2839be0ab7f01fedf>:0 
     - PREFIX TKS_Ragdoll: Boolean TKS_Ragdoll.Thing_patches:Kill_prefix(DamageInfo dinfo, Hediff exactCulprit, Thing __instance)
 at Verse.ThingWithComps.Kill (System.Nullable`1[T] dinfo, Verse.Hediff exactCulprit) [0x00024] in <91ef6de66e7b4ba2839be0ab7f01fedf>:0 
 at Verse.Pawn.Kill (System.Nullable`1[T] dinfo, Verse.Hediff exactCulprit) [0x005dc] in <91ef6de66e7b4ba2839be0ab7f01fedf>:0 
     - PREFIX TKS_Ragdoll: Boolean TKS_Ragdoll.Pawn_patches:Kill_Prefix(Nullable`1 dinfo, Hediff exactCulprit, Pawn __instance)

**Comment by Rex5522** [comment]
np and thanks for trying to resolve the issue

with ragdoll logs enabled: https://gist.github.com/HugsLibRecordKeeper/9cd750ba358c0879bdd42127b3c4dddf
heres another log as i saw a new error that i havent seen before (near the bottom): https://gist.github.com/HugsLibRecordKeeper/09a4dc0132b50bc77842f94665ff975d

here is some additional detail on recreating the issue (how i find the issue atleast)
dev mode is enabled
check modlist at the top of the hubs lib log to see the enabled mods / order of mods
load dev quick test (or just a normal save)
use dev pallet to spawn around 100 "mercenary_sniper_acidifier"
important: then use morters or even just the dev pallet explosive spawn. pause the game and spawn around 10-20 explosions (dont vaporize them. they need to ragdoll so put the explosions off to the side of the group but not to far of to the side)

**Comment by tk421storm** [comment]
these steps were great thank you! I was able to pinpoint what I think the issue was, please try the latest version and see how it works for you (either from here or on steam workshop)

**Comment by Rex5522** [comment]
i was doing some testing with the old version (before i forced steam to update it) and the error was occurring with the auto mortars mod disabled so this might not have been a mod clash? but ether way i dont seem to be able to recreate the issue with or without the automortars mod enabled no matter how hard i try, this is awesome! thanks! (i code java so i dont know much c but what was the issue if you wish to share?)

**Comment by tk421storm** [comment]
that's great to hear! Yeah I'm mainly a python guy but with c# the main thing is those 'null reference' errors - variables can be null and if you don't handle that somehow beforehand (if x!=null) then it will hault with a really unhelpful message (at least python will say something like "None-type has no attribute blowUp".

In this case, when a pawn dies, I want to toss the corpse. So during the "kill" function I attempt to stop the toss of the pawn, and start the toss of the pawn's corpse on the same trajectory. I just added an early escape to my stop function (that includes other nice-to-have bits like impact damage) with a "dead=true" flag - if the pawn died, just reset the core variables for tossing and break out early. That seems to have fixed it!

**Comment by Rex5522** [comment]
makes sense and nice! alright ill close this issue now, if you need some help bug testing or something feel free to msg me on discord. have a good time! and thanks for fixing the issue
